### ISSUE TITLE
Tab order in the GUI is messed up

### ISSUE THREAD

**Issue by RPiAwesomeness** [RPiAwesomeness/Keyboard-Mail-Desktop#3]
If you select the recipient(s)/To field and then press tab, it tabs in a strange order:

`To --> Unknown field (cursor disappears) --> BCC --> CC --> Subject.`

What it *should* be (logical progression):

`To --> CC --> BCC --> Subject`

**Comment by nathan-osman** [comment]
I'll take a look at this one. Incidentally, it appears that the "unknown field" that received focus after the "To" entry box is the send button.

**Comment by RPiAwesomeness** [comment]
Apparently github didn't recognize it, but this was fixed by @nathan-osman's pull request.
